module: react-render
runtime: nodejs
vm: true

# TODO(jlfwong): Figure out what the right scaling policy is
automatic_scaling:
  min_num_instances: 2
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.5
