// flow-typed signature: 6a6e86d48943ac58c429e2a64e334673
// flow-typed version: <<STUB>>/superagent_v^4.0.0/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'superagent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'superagent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'superagent/dump' {
  declare module.exports: any;
}

declare module 'superagent/lib/agent-base' {
  declare module.exports: any;
}

declare module 'superagent/lib/client' {
  declare module.exports: any;
}

declare module 'superagent/lib/is-object' {
  declare module.exports: any;
}

declare module 'superagent/lib/node/agent' {
  declare module.exports: any;
}

declare module 'superagent/lib/node/http2wrapper' {
  declare module.exports: any;
}

declare module 'superagent/lib/node' {
  declare module.exports: any;
}

declare module 'superagent/lib/node/parsers/image' {
  declare module.exports: any;
}

declare module 'superagent/lib/node/parsers' {
  declare module.exports: any;
}

declare module 'superagent/lib/node/parsers/json' {
  declare module.exports: any;
}

declare module 'superagent/lib/node/parsers/text' {
  declare module.exports: any;
}

declare module 'superagent/lib/node/parsers/urlencoded' {
  declare module.exports: any;
}

declare module 'superagent/lib/node/response' {
  declare module.exports: any;
}

declare module 'superagent/lib/node/unzip' {
  declare module.exports: any;
}

declare module 'superagent/lib/request-base' {
  declare module.exports: any;
}

declare module 'superagent/lib/response-base' {
  declare module.exports: any;
}

declare module 'superagent/lib/utils' {
  declare module.exports: any;
}

declare module 'superagent/superagent' {
  declare module.exports: any;
}

declare module 'superagent/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'superagent/dump.js' {
  declare module.exports: $Exports<'superagent/dump'>;
}
declare module 'superagent/lib/agent-base.js' {
  declare module.exports: $Exports<'superagent/lib/agent-base'>;
}
declare module 'superagent/lib/client.js' {
  declare module.exports: $Exports<'superagent/lib/client'>;
}
declare module 'superagent/lib/is-object.js' {
  declare module.exports: $Exports<'superagent/lib/is-object'>;
}
declare module 'superagent/lib/node/agent.js' {
  declare module.exports: $Exports<'superagent/lib/node/agent'>;
}
declare module 'superagent/lib/node/http2wrapper.js' {
  declare module.exports: $Exports<'superagent/lib/node/http2wrapper'>;
}
declare module 'superagent/lib/node/index' {
  declare module.exports: $Exports<'superagent/lib/node'>;
}
declare module 'superagent/lib/node/index.js' {
  declare module.exports: $Exports<'superagent/lib/node'>;
}
declare module 'superagent/lib/node/parsers/image.js' {
  declare module.exports: $Exports<'superagent/lib/node/parsers/image'>;
}
declare module 'superagent/lib/node/parsers/index' {
  declare module.exports: $Exports<'superagent/lib/node/parsers'>;
}
declare module 'superagent/lib/node/parsers/index.js' {
  declare module.exports: $Exports<'superagent/lib/node/parsers'>;
}
declare module 'superagent/lib/node/parsers/json.js' {
  declare module.exports: $Exports<'superagent/lib/node/parsers/json'>;
}
declare module 'superagent/lib/node/parsers/text.js' {
  declare module.exports: $Exports<'superagent/lib/node/parsers/text'>;
}
declare module 'superagent/lib/node/parsers/urlencoded.js' {
  declare module.exports: $Exports<'superagent/lib/node/parsers/urlencoded'>;
}
declare module 'superagent/lib/node/response.js' {
  declare module.exports: $Exports<'superagent/lib/node/response'>;
}
declare module 'superagent/lib/node/unzip.js' {
  declare module.exports: $Exports<'superagent/lib/node/unzip'>;
}
declare module 'superagent/lib/request-base.js' {
  declare module.exports: $Exports<'superagent/lib/request-base'>;
}
declare module 'superagent/lib/response-base.js' {
  declare module.exports: $Exports<'superagent/lib/response-base'>;
}
declare module 'superagent/lib/utils.js' {
  declare module.exports: $Exports<'superagent/lib/utils'>;
}
declare module 'superagent/superagent.js' {
  declare module.exports: $Exports<'superagent/superagent'>;
}
declare module 'superagent/test.js' {
  declare module.exports: $Exports<'superagent/test'>;
}
